require: rubocop-rspec

AllCops:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'app/models/concerns/**/*'
    - 'spec/controllers/**/*'
    - 'spec/helpers/**/*'
    - 'spec/models/**/*'
    - 'spec/policies/**/*'
    - 'spec/requests/**/*'
    - 'spec/routing/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/controllers/**/*'

PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': ()

Style/BlockDelimiters:
  Exclude:
    - 'spec/controllers/**/*'

Layout/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Rails:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/controllers/**/*'
    - 'spec/helpers/**/*'
    - 'spec/requests/**/*'
    - 'spec/views/**/*'

RSpec/ExpectActual:
  Exclude:
    - 'spec/routing/**/*'

RSpec/RepeatedExample:
  Exclude:
    - 'spec/policies/**/*'

RSpec/RepeatedDescription:
  Exclude:
    - 'spec/policies/**/*'
